# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    timeout-minutes: 20
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:<
          node-version: 16

      - name: Install backend dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install frontend dependences
        run: cd frontend; npm install; cd ..
      
      - name: Build frontend
        run: cd frontend; npm run build; cd ..
      
      - name: Run app
        run: npm start &

      - name: Run Backend tests
        run: npm test
      
      - name: Run e2e tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
    
      - name: Deploy
        run: gcloud app deploy