# .github/workflows/deploy.yml
name: Deploy to Cloud Run & Playwright e2e tests
on:
  push:
    branches:
      - main
jobs:
  deploy:
    timeout-minutes: 20
    name: Deploy to Google Cloud Run & Playwright e2e tests
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Install Playwright Browsers'
        run: npx playwright install --with-deps
      - name: 'Actualizando frontend producción'
        run: cd frontend; npm install;npm run build;cd ..
      - name: 'Inicia servidor node'
        run: npm start & 
      - name: 'Pruebas métodos backend'
        run: npm test
      - name: 'Run Playwright e2e tests'
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: Deploy
        run: gcloud app deploy
    